//
//  LanguageList.swift
//  caption
//
//  Created by Wouter van de Kamp on 25/02/2017.
//  Copyright © 2017 Wouter van de Kamp. All rights reserved.
//

import Foundation

struct LanguageList {
    static var languageDict = [
        "Afrikaans": "afr",
        "Albanian": "alb",
        "Arabic": "ara",
        "Armenian": "arm",
        "Basque": "baq",
        "Belarusian": "bel",
        "Bengali": "ben",
        "Bosnian": "bos",
        "Breton": "bre",
        "Bulgarian": "bul",
        "Burmese": "bur",
        "Catalan": "cat",
        "Chinese (simplified)": "chi",
        "Chinese (traditional)": "zht",
        "Chinese bilingual": "zhe",
        "Croatian": "hrv",
        "Czech": "cze",
        "Danish": "dan",
        "Dutch": "dut",
        "English": "eng",
        "Esperanto": "epo",
        "Estonian": "est",
        "Finnish": "fin",
        "French": "fre",
        "Galician": "glg",
        "Georgian": "geo",
        "German": "ger",
        "Greek": "ell",
        "Hebrew": "heb",
        "Hindi": "hin",
        "Hungarian": "hun",
        "Icelandic": "ice",
        "Indonesian": "ind",
        "Italian": "ita",
        "Japanese": "jpn",
        "Kazakh": "kaz",
        "Khmer": "khm",
        "Korean": "kor",
        "Latvian": "lav",
        "Lithuanian": "lit",
        "Luxembourgish": "ltz",
        "Macedonian": "mac",
        "Malay": "may",
        "Malayalam": "mal",
        "Manipuri": "mni",
        "Mongolian": "mon",
        "Montenegrin": "mne",
        "Norwegian": "nor",
        "Occitan": "oci",
        "Persian": "per",
        "Polish": "pol",
        "Portuguese": "por",
        "Portuguese (BR)": "pob",
        "Romanian": "rum",
        "Russian": "rus",
        "Serbian": "scc",
        "Sinhalese": "sin",
        "Slovak": "slo",
        "Slovenian": "slv",
        "Spanish": "spa",
        "Swahili": "swa",
        "Swedish": "swe",
        "Syriac": "syr",
        "Tagalog": "tgl",
        "Tamil": "tam",
        "Telugu": "tel",
        "Thai": "tha",
        "Turkish": "tur",
        "Ukrainian": "ukr",
        "Urdu": "urd",
        "Vietnamese": "vie"
    ] as NSDictionary
}
